Cauldron2/Cauldron2/urls.py
from django.contrib import admin
from django.urls import path, include
from CauldronApp import views

urlpatterns = [
    path('github-login', views.request_github_login_callback),
    path('gitlab-login', views.request_gitlab_login_callback),
    path('meetup-login', views.request_meetup_login_callback),
    path('logout', views.request_logout),
    path('delete-token', views.request_delete_token),

    path('projects', views.request_user_projects, name="projectspage"),

    path('dashboard', views.request_new_dashboard),
    path('dashboard/<int:dash_id>', views.request_show_dashboard, name="show_dashboard"),
    path('dashboard/<int:dash_id>/edit', views.request_edit_dashboard),
    path('dashboard/<int:dash_id>/edit-name', views.request_edit_dashboard_name),
    path('dashboard/<int:dash_id>/info', views.request_dash_info),
    path('dashboard/<int:dash_id>/summary', views.request_dash_summary),
    path('dashboard/<int:dash_id>/kibana', views.request_kibana, name="open_kibana"),
    path('dashboard/<int:dash_id>/delete', views.request_delete_dashboard, name="delete_project_url"),
    path('dashboard/<int:dash_id>/public-kibana', views.request_public_kibana, name="open_public_kibana"),

    path('repo-logs/<int:repo_id>', views.repo_logs),

    path('admin-page', views.admin_page, name="admin_page"),
    path('profile/', include('profile.urls')),

    path('', views.homepage, name="homepage"),
    path('admin/', admin.site.urls),
]

Cauldron2/profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'
urlpatterns = [
    path('', views.index, name='index'),
]

Cauldron2/CauldronApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# IMPORTANT: If you are going to modify any User Reference: take a look at merge_accounts in views.py

# IMPORTANT: If you are going to change the schema, you MUST modify the schema in mordred container


class AnonymousUser(models.Model):
    # When an anonymous user creates a dashboard they are linked to a entry in this model
    # When they log in with some account this entry will be deleted so they will not be anonymous anymore
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)


class Token(models.Model):
    STATUS_READY = 'ready'
    STATUS_COOLDOWN = 'cooldown'

    backend = models.CharField(max_length=100)
    key = models.CharField(max_length=200)
    rate_time = models.DateTimeField(null=True, auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def status(self):
        if self.rate_time <= timezone.now():
            return self.STATUS_READY

        return self.STATUS_COOLDOWN

    def is_ready(self):
        return self.status == self.STATUS_READY


class GithubUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    username = models.CharField(max_length=100)
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    photo = models.URLField()


class GitlabUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    username = models.CharField(max_length=100)
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    photo = models.URLField()


class MeetupUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    username = models.CharField(max_length=100)
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    refresh_token = models.CharField(max_length=100)
    photo = models.URLField()


class Dashboard(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User,
                                on_delete=models.SET_NULL,
                                blank=True,
                                null=True)


class ESUser(models.Model):
    name = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE)
    private = models.BooleanField(default=True)


class Repository(models.Model):
    """
    Available backends: github, gitlab, meetup and git
    """
    url = models.URLField()
    backend = models.CharField(max_length=100)
    dashboards = models.ManyToManyField(Dashboard)


class Task(models.Model):
    """
    When a worker takes one:
    - Update the worker ID
    - Update the started date
    When a worker finishes one:
    - Create a completedTask
    - Delete this task
    """
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)
    worker_id = models.CharField(max_length=255, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    started = models.DateTimeField(null=True)
    retries = models.IntegerField(default=0)
    log_file = models.CharField(max_length=255, blank=True)
    tokens = models.ManyToManyField(Token)


class CompletedTask(models.Model):
    task_id = models.IntegerField()
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)
    created = models.DateTimeField()
    started = models.DateTimeField()
    completed = models.DateTimeField()
    retries = models.IntegerField()
    status = models.CharField(max_length=255)
    log_file = models.CharField(max_length=255, blank=True)
    old = models.BooleanField(default=False)

Cauldron2/CauldronApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import transaction
from django.db.models import Count, F

import os
import jwt
import re
import logging
import requests
from random import choice
from github import Github
from gitlab import Gitlab
from string import ascii_lowercase, digits
from urllib.parse import urlparse, urlencode
import time

from Cauldron2.settings import GH_CLIENT_ID, GH_CLIENT_SECRET, GL_CLIENT_ID, GL_CLIENT_SECRET, \
                                MEETUP_CLIENT_ID, MEETUP_CLIENT_SECRET, \
                                ES_IN_HOST, ES_IN_PORT, ES_IN_PROTO, ES_ADMIN_PSW, \
                                KIB_IN_HOST, KIB_IN_PORT, KIB_IN_PROTO, KIB_OUT_URL, \
                                KIB_PATH, HATSTALL_ENABLED, HATSTALL_URL, GOOGLE_ANALYTICS_ID
from CauldronApp.models import GithubUser, GitlabUser, MeetupUser, Dashboard, Repository, Task, \
                               CompletedTask, AnonymousUser, ESUser, Token
from CauldronApp.githubsync import GitHubSync
from CauldronApp.opendistro_utils import OpendistroApi

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

GH_ACCESS_OAUTH = 'https://github.com/login/oauth/access_token'
GH_URI_IDENTITY = 'https://github.com/login/oauth/authorize'

GL_ACCESS_OAUTH = 'https://gitlab.com/oauth/token'
GL_URI_IDENTITY = 'https://gitlab.com/oauth/authorize'
GL_REDIRECT_PATH = '/gitlab-login'

MEETUP_ACCESS_OAUTH = 'https://secure.meetup.com/oauth2/access'
MEETUP_URI_IDENTITY = 'https://secure.meetup.com/oauth2/authorize'
MEETUP_REDIRECT_PATH = '/meetup-login'

DASHBOARD_LOGS = '/dashboard_logs'

BACKEND_INDICES = [
    {
        "name": "git_aoc_enriched_index",
        "backend": "git",
        "url_field": "repository"
    },
    {
        "name": "git_enrich_index",
        "backend": "git",
        "url_field": "repo_name"
    },
    {
        "name": "github_enrich_index",
        "backend": "github",
        "url_field": "repository"
    },
    {
        "name": "gitlab_enriched_index",
        "backend": "gitlab",
        "url_field": "repository"
    },
    {
        "name": "meetup_enriched_index",
        "backend": "meetup",
        "url_field": "tag"
    },
]


ES_IN_URL = "{}://{}:{}".format(ES_IN_PROTO, ES_IN_HOST, ES_IN_PORT)
KIB_IN_URL = "{}://{}:{}{}".format(KIB_IN_PROTO, KIB_IN_HOST, KIB_IN_PORT, KIB_PATH)

ES_INDEX_SUFFIX = "index"

logger = logging.getLogger(__name__)


def homepage(request):
    context = create_context(request)

    return render(request, 'index.html', context=context)


def request_user_projects(request):
    context = create_context(request)
    if not request.user.is_authenticated:
        context['title'] = "You are not logged in"
        context['description'] = "You need to login or create a new project to continue"
        return render(request, 'error.html', status=400, context=context)
    else:
        projects = Dashboard.objects.filter(creator=request.user)
        projects_info = list()
        for project in projects:
            repositories = Repository.objects.filter(dashboards=project.pk)
            n_completed = CompletedTask.objects.filter(repository__in=repositories, status='COMPLETED', old=False).count()
            n_errors = CompletedTask.objects.filter(repository__in=repositories, status='ERROR', old=False).count()
            n_pending = Task.objects.filter(repository__in=repositories).count()
            projects_info.append({
                'project': project,
                'completed': n_completed,
                'errors': n_errors,
                'pending': n_pending,
                'total': n_completed + n_errors + n_pending
            })
        context['projects_info'] = projects_info
    return render(request, 'projects.html', context=context)


# TODO: Add state
def request_github_login_callback(request):
    context = create_context(request)

    # Github authentication
    code = request.GET.get('code', None)
    if not code:
        context['title'] = "Bad Request"
        context['description'] = "There isn't a code in the GitHub callback"
        return render(request, 'error.html', status=400,
                      context=context)

    r = requests.post(GH_ACCESS_OAUTH,
                      data={'client_id': GH_CLIENT_ID,
                            'client_secret': GH_CLIENT_SECRET,
                            'code': code},
                      headers={'Accept': 'application/json'})
    if r.status_code != requests.codes.ok:
        logging.error('GitHub API error %s %s %s', r.status_code, r.reason, r.text)
        context['title'] = "GitHub error"
        context['description'] = "GitHub API error"
        return render(request, 'error.html', status=500,
                      context=context)
    token = r.json().get('access_token', None)
    if not token:
        logging.error('ERROR GitHub Token not found. %s', r.text)
        context['title'] = "GitHub error"
        context['description'] = "Error getting the token from GitHub endpoint"
        return render(request, 'error.html', status=500,
                      context=context)

    # Authenticate/register an user, and login
    gh = Github(token)
    gh_user = gh.get_user()
    username = gh_user.login
    photo_url = gh_user.avatar_url

    # Get data from session
    data_add = request.session.get('add_repo', None)
    last_page = request.session.get('last_page', None)

    tricky_authentication(request, GithubUser, username, username, token, photo_url)

    # Get the previous state
    if data_add:
        dash = Dashboard.objects.filter(id=data_add['dash_id']).first()
        # Only GitHub, is the new account added
        if data_add['backend'] == 'github':
            commits = data_add['commits']
            issues = data_add['issues']
            manage_add_gh_repo(dash, data_add['data'], commits, issues)

    if last_page:
        return HttpResponseRedirect(last_page)

    return HttpResponseRedirect('/')


def merge_accounts(user_origin, user_dest):
    """
    Change the references of that user to another one
    :param user_origin: User to delete
    :param user_dest: User to keep
    :return:
    """
    gh_users = GithubUser.objects.filter(user=user_origin)
    for gh_user in gh_users:
        gh_user.user = user_dest
        gh_user.save()
    gl_users = GitlabUser.objects.filter(user=user_origin)
    for gl_user in gl_users:
        gl_user.user = user_dest
        gl_user.save()
    mu_users = MeetupUser.objects.filter(user=user_origin)
    for mu_user in mu_users:
        mu_user.user = user_dest
        mu_user.save()
    dashs = Dashboard.objects.filter(creator=user_origin)
    for dash in dashs:
        dash.creator = user_dest
        dash.save()
    tokens = Token.objects.filter(user=user_origin)
    for token in tokens:
        token.user = user_dest
        token.save()


# TODO: Add state
def request_gitlab_login_callback(request):
    context = create_context(request)

    # Gitlab authentication
    code = request.GET.get('code', None)
    if not code:
        context['title'] = "Bad Request"
        context['description'] = "There isn't a code in the GitLab callback"
        return render(request, 'error.html', status=400,
                      context=context)
    r = requests.post(GL_ACCESS_OAUTH,
                      params={'client_id': GL_CLIENT_ID,
                              'client_secret': GL_CLIENT_SECRET,
                              'code': code,
                              'grant_type': 'authorization_code',
                              'redirect_uri': "https://{}{}".format(request.get_host(), GL_REDIRECT_PATH)},
                      headers={'Accept': 'application/json'})

    if r.status_code != requests.codes.ok:
        logging.error('Gitlab API error %s %s', r.status_code, r.reason)
        context['title'] = "Gitlab error"
        context['description'] = "Gitlab API error"
        return render(request, 'error.html', status=500,
                      context=context)
    token = r.json().get('access_token', None)
    if not token:
        logging.error('ERROR Gitlab Token not found. %s', r.text)
        context['title'] = "Gitlab error"
        context['description'] = "Error getting the token from Gitlab endpoint"
        return render(request, 'error.html', status=500,
                      context=context)

    # Authenticate/register an user, and login
    gl = Gitlab(url='https://gitlab.com', oauth_token=token)
    gl.auth()
    username = gl.user.attributes['username']
    photo_url = gl.user.attributes['avatar_url']

    # Get data from session
    data_add = request.session.get('add_repo', None)
    last_page = request.session.get('last_page', None)

    tricky_authentication(request, GitlabUser, username, username, token, photo_url)

    # Get the previous state
    if data_add:
        dash = Dashboard.objects.filter(id=data_add['dash_id']).first()
        # Only GitLab, is the new account added
        if data_add['backend'] == 'gitlab':
            commits = data_add['commits']
            issues = data_add['issues']
            manage_add_gl_repo(dash, data_add['data'], commits, issues)

    if last_page:
        return HttpResponseRedirect(last_page)

    return HttpResponseRedirect('/')


# TODO: Add state
def request_meetup_login_callback(request):
    context = create_context(request)

    # Meetup authentication
    error = request.GET.get('error', None)
    if error:
        context['title'] = "Error from Meetup Oauth"
        context['description'] = error
        return render(request, 'error.html', status=400,
                      context=context)
    code = request.GET.get('code', None)
    if not code:
        context['title'] = "Bad Request"

Cauldron2/CauldronApp/templates/base.html
{% load static %}

{% url 'projectspage' as projectspage %}
{% url 'homepage' as homepage %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Software development analytics online tool by Bitergia">

  <!-- Cookie consent -->
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
  <script>
  window.addEventListener("load", function(){
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#edeff5",
        "text": "#838391"
      },
      "button": {
        "background": "#4b81e8"
      }
    },
    "showLink": false,
    "position": "bottom-right",
    "content": {
      "message": "This website uses cookies to remember your preferences, and to learn about how people are using the system."
    }
  })});
  </script>

  {% if google_analytics_id %}
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id={{ google_analytics_id }}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '{{google_analytics_id}}');
  </script>
  {% endif %}

  <!-- SB Admin 2 styles -->
  <link rel="stylesheet" href="{% static 'css/sb-admin-2.min.css' %}">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Awesome icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/smart-nav.css' %}">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  <!-- Favicon.ico -->
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>
  {% block css%}
  {% endblock %}

  <title>Cauldron - Level Up Software Development Analytics</title>
</head>

<body>
  <!-- BEGIN NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand mr-auto" href="{% url 'homepage' %}">
        <img src="{% static '/img/cauldron-logo-white.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Cauldron <sup class="badge badge-secondary">dijon</sup>
      </a>
      {% if authenticated %}
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto ml-3">
          <li class="nav-item {% ifequal request.path homepage %}active{% endifequal %}">
            <a class="nav-link" href="{% url 'homepage' %}">Home</a>
          </li>
          <li class="nav-item {% ifequal request.path projectspage %}active{% endifequal %}">
            <a class="nav-link" href="{% url 'projectspage' %}">My Projects</a>
          </li>
        </ul>
      </div>
      {% endif %}
      <!--<ul class="navbar-nav flew-row ml-md-auto d-none d-md-flex">
        <li class="nav-item">
          <a href="https://gitlab.com/cauldronio/cauldron" target="_blank" rel="noopener" aria-label="GitLab" class="nav-link p2">
            <i class="fab fa-gitlab"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="https://twitter.com/biterg_cauldron" target="_blank" rel="noopener" aria-label="Twitter" class="nav-link p2">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
      </ul>-->

      <div class="navbar-line d-none"></div>

      {% if authenticated %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle navbar-text py-0" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span> {{ request.user.first_name }} </span>
          <img src="{{ photo_user }}" class="rounded-circle avatar">
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

          {% if request.user.is_superuser %}
          <a class="dropdown-item" href="{% url 'admin_page' %}">Admin page</a>
          {% endif %}
          {% if request.user.is_superuser and hatstall_url %}
          <a class="dropdown-item" href="{{ hatstall_url }}">Hatstall</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'projectspage' %}">My projects</a>
          <a class="dropdown-item" href="{% url 'profile:index' %}">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/logout">Log out</a>
          <!--<a class="dropdown-item" href="/profile">Profile</a>-->
        </div>
      </div>
      {% else %}
      <a class="btn btn-light d-block d-lg-inline-block mb-0 ml-md-3" href="#" data-toggle="modal" data-target="#modalLogin">
        Login
      </a>
      {% endif %}

    </div>
  </nav>
  <!-- END NAVBAR-->

  <!-- BEGIN Smart Nav-->
  <div id="cd-nav" class="is-fixed">
		<a href="#0" class="cd-nav-trigger">Menu<span></span></a>
		<nav id="cd-main-nav">
			<ul>
				<li><a href="https://community.cauldron.io/" target="_blank">Get Support</a></li>
				<li><a href="https://gitlab.com/cauldronio/cauldron/issues/new" target="_blank">Report an Issue</a></li>
				<li><a href="https://mailchi.mp/003f1e1f6242/cauldron-newsletter" target="_blank">Join the Newsletter</a></li>
			</ul>
		</nav>
	</div>
  <!-- END Smart Nav-->

  <!-- BEGIN Modal for login -->
  <div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="modalLoginTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="col-12 text-center">Sign in</h3>
        </div>
        <div class="modal-body">

          <div class="text-center">
            <form action="{{ gh_uri_identity }}" method="GET">
              <input type="hidden" name="client_id" value="{{ gh_client_id }}">
              <button type="submit" class="btn btn-github btn-block" aria-haspopup="true" aria-expanded="false">
                <i class="fab fa-github"></i>
                Sign in with <b>GitHub</b>
              </button>
            </form>
          </div>

          <div class="text-center">
            <form action="{{ gl_uri_identity }}" method="GET">
              <input type="hidden" name="client_id" value="{{ gl_client_id }}">
              <input type="hidden" name="response_type" value="code">
              <input type="hidden" name="redirect_uri" value="{{ gl_uri_redirect }}">
              <button type="submit" class="btn btn-gitlab btn-block" aria-haspopup="true" aria-expanded="false">
                <i class="fab fa-gitlab"></i>
                Sign in with <b>GitLab</b>
              </button>
            </form>
          </div>

          <div class="text-center">
            <form action="{{ meetup_uri_identity }}" method="GET">
              <input type="hidden" name="client_id" value="{{ meetup_client_id }}">
              <input type="hidden" name="response_type" value="code">
              <input type="hidden" name="redirect_uri" value="{{ meetup_uri_redirect }}">
              <button type="submit" class="btn btn-meetup btn-block" aria-haspopup="true" aria-expanded="false">
                <i class="fab fa-meetup"></i>
                Sign in with <b>Meetup</b>
              </button>
            </form>
          </div>

        </div>
        <div class="modal-footer">
          <p class="text-muted">We will store your token for your analysis. You can revoke the use at any time</p>
        </div>
      </div>
    </div>
  </div>
  <!-- END Modal for login -->



  <!-- BEGIN Container for alerts -->
  <div class="container">
    <div id="alert-container" style="display: none;">
    </div>
  </div>
  <!-- END Container for alerts-->


  <!-- BEGIN Container for modals -->
  <div class="modal" tabindex="-1" role="dialog" id="modal-alert">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p></p>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- END Container for modals-->


  <!-- BEGIN Toast list for notifications-->
  <div aria-live="polite" aria-atomic="true" style="position: fixed; width: 100%; bottom: 50px; z-index: 9999;">
    <!-- Position it -->
    <div id="toast-container">

    </div>
  </div>
  <!-- END Toast list for notifications-->

  <div class="site-content">
  {% block content %}
  {% endblock %}
  </div>


  <footer class="container-fluid footer-position bg-dark text-white pt-3">

    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="full-footer"><a href="https://bitergia.com" target="_blank"><img class="mx-auto d-block" src="/static/img/bitergia-w-logo-s.png" style="float:left" alt="Bitergia"></a></div>
            <p style="display:inline-block">Copyright &copy; 2019 <a href="https://bitergia.com">Bitergium SLL.</a> and its
              contributors.</p>
            <p class="full-footer">Some Rights Reserved.</p>
        </div>
        <div class="col-md-4">
          <p class="text-justify full-footer">Unless otherwise stated, this work is licensed under a <strong>Creative
              Commons Attribution-ShareAlike 4.0 Unported License</strong>. Cauldron and the Cauldron logo are
            trademarks of <a href="https://bitergia.com" target="_blank">Bitergium SLL.</a> in the European Union and/or
            other jurisdictions. All other trademarks are the property of their respective holders.</p>
        </div>
        <div class="col-md-4">
          <p class="full-footer">Made with <abbr title="love">&hearts;</abbr> and <strong>free, open source software</strong>:</p>
          <p class="full-footer"><a href="https://chaoss.github.io/grimoirelab/" target="_blank"><img src="/static/img/wizard-y.svg"
                height="24" alt=""> GrimoireLab</a></p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
  <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

  <script src="{% static 'js/common.js' %}" charset="utf-8"></script>
  <script src="{% static 'js/smart-nav.js' %}"></script>

  {% block javascript %}
  {% endblock %}
</body>

</html>

Cauldron2/CauldronApp/templates/delete_project.html
<!-- Modal delete project -->
<div class="modal fade" id="modal-delete-project" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you absolutely sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
				<p>This cannot be undone. The following actions will be performed:</p>
				<ul>
					<li>The project will be removed</li>
					<li>The tasks associated to this project will be stopped as soon as possible</li>
					<li>You will lose the visualizations created in Kibana</li>
				</ul>
				<p>Please, confirm you want to delete the project <span id="delete-project-name" class="font-weight-bold"></span></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="" method="post" id="form-delete-project">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">Delete project</button>
        </form>
      </div>
    </div>
  </div>
</div>